apiVersion: apps/v1
kind: Deployment
metadata:
  name: despachos-backend
  namespace: ep3
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: despachos-backend
  template:
    metadata:
      labels:
        app: despachos-backend
    spec:
      containers:
        - name: despachos-backend
          image: 171210198405.dkr.ecr.us-east-1.amazonaws.com/ep3-despachos-backend:eks-v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SERVER_PORT
              value: "8081"
            - name: DB_ENDPOINT
              value: mysql-db
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: despachos_db
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "768Mi"
