apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
  namespace: ep3
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS despachos_db;
    CREATE DATABASE IF NOT EXISTS ventas_db;

    CREATE USER IF NOT EXISTS 'appuser'@'%' IDENTIFIED BY 'app123';

    GRANT ALL PRIVILEGES ON despachos_db.* TO 'appuser'@'%';
    GRANT ALL PRIVILEGES ON ventas_db.* TO 'appuser'@'%';

    FLUSH PRIVILEGES;
